[package]
name = "julia_set"
version = "0.1.0"
authors = ["Tim de Klijn <timdeklijn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
palette = "0.5"
structopt = "0.3"